resources:
  - url: http://127.0.0.1:5000/tadothermostat-card.js
    type: module
views:
  - cards:
      - type: custom:tadothermostat-card
        name: Tadothermostat Card Development
        entity: climate.hallway
        test_gui: true
